apiVersion: v1
kind: Namespace
metadata:
  name: mriquelme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: mriquelme
data:
  USERNAME: "usuario-demo"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: mriquelme
type: Opaque
data:
  API_KEY: dGVzdGtleQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mriquelme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mrviacava/backend-devops:9   # o :latest
          ports:
            - containerPort: 3000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: USERNAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: API_KEY
      imagePullSecrets: []   
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mriquelme
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
